version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ":10001"
    networks:
      - shared
    env_file:
      - .env
    volumes:
      - /opt/ipban/logs:/app/logs
    depends_on:
      - redis
      - mongodb
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
          ignore:
            - .git/
            - .venv/
            - __pycache__/
            - "*.pyc"
        - action: rebuild
          path: requirements.txt

  redis:
    image: redis:latest
    container_name: redis
    restart: "no"
    ports:
      - ":6379"
    volumes:
      - redis_data:/data
    networks:
      - shared

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: "no"
    ports:
      - ":27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - shared

volumes:
  mongodb_data:
  redis_data:

networks:
  shared:
    external: true
    name: shared_db_net